f=input('Enter food item name:\n')
p=float(input('Enter item price:\n'))
q=int(input('Enter item quantity:\n'))
print()
print("RECEIPT")
print('{} {} @ ${:.2f} = ${:.2f}'.format(q, f, p, (p*q)))
print('Total cost: ${:.2f}'.format(p*q))
#print('Total cost: $',float(q*p))
# FIXME (2): Read in a second food item name, price, and quantity, then output a second receipt
print()
print()
# FIXME (3): Add a gratuity and total with tip to the second receipt
#t1 = p*q

f1 = input('Enter second food item name:\n')
p1 = float(input('Enter item price:\n'))
q1 = int(input('Enter item quantity:\n'))
print()
print("RECEIPT")
print('{} {} @ ${:.2f} = ${:.2f}'.format(q, f, p, (p*q)))
print('{} {} @ ${:.2f} = ${:.2f}'.format(q1, f1, p1, (p1*q1)))
print('Total cost: ${:.2f}'.format((p*q)+(q1*p1)))
print()
t1 = float(p*q)
t2 = float(p1*q1)
tip = float((t1+t2) *.15)
k= float(tip+t1+t2)
print('15% gratuity: ${:.2f}'.format(tip))
print('Total with tip: ${:.2f}'.format(k))
